/**
 * WhatsApp Integration Service for Kiara
 * Uses Twilio WhatsApp Business API for sending/receiving messages
 * Server-side webhook handles incoming messages and routes to AI processing
 */

import { db, auth } from '../lib/firebase';
import { collection, addDoc, query, where, orderBy, limit, getDocs, serverTimestamp, onSnapshot } from 'firebase/firestore';

export interface WhatsAppMessage {
  id?: string;
  from: string;
  to: string;
  body: string;
  direction: 'incoming' | 'outgoing';
  status: 'queued' | 'sent' | 'delivered' | 'read' | 'failed';
  mediaUrl?: string;
  mediaType?: string;
  timestamp: any;
  userId: string;
  isProcessed: boolean;
}

export interface WhatsAppContact {
  phoneNumber: string;
  name: string;
  lastMessage?: string;
  lastMessageTime?: Date;
  unreadCount: number;
}

class WhatsAppService {
  private baseUrl: string;

  constructor() {
    // Server endpoint handles Twilio API calls securely
    this.baseUrl = `${window.location.origin}/api/whatsapp`;
  }

  /**
   * Send a WhatsApp message via the server proxy
   */
  async sendMessage(to: string, body: string, mediaUrl?: string): Promise<{ success: boolean; messageId?: string; error?: string }> {
    if (!auth.currentUser) throw new Error("User not authenticated");

    try {
      const response = await fetch(`${this.baseUrl}/send`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          to,
          body,
          mediaUrl,
          userId: auth.currentUser.uid
        })
      });

      const data = await response.json();

      if (data.success) {
        // Store outgoing message in Firestore
        await addDoc(collection(db, 'whatsapp_messages'), {
          from: 'kiara',
          to,
          body,
          direction: 'outgoing',
          status: 'sent',
          mediaUrl: mediaUrl || null,
          timestamp: serverTimestamp(),
          userId: auth.currentUser.uid,
          isProcessed: true,
          twilioSid: data.messageId
        });
      }

      return data;
    } catch (error: any) {
      console.error("WhatsApp send error:", error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Send a smart reply generated by AI based on context
   */
  async sendSmartReply(to: string, incomingMessage: string, context?: string): Promise<{ success: boolean; reply?: string; error?: string }> {
    if (!auth.currentUser) throw new Error("User not authenticated");

    try {
      const response = await fetch(`${this.baseUrl}/smart-reply`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          to,
          incomingMessage,
          context,
          userId: auth.currentUser.uid
        })
      });

      return await response.json();
    } catch (error: any) {
      console.error("WhatsApp smart reply error:", error);
      return { success: false, error: error.message };
    }
  }

  /**
   * Get conversation history with a specific contact
   */
  async getConversation(phoneNumber: string, messageLimit: number = 50): Promise<WhatsAppMessage[]> {
    if (!auth.currentUser) throw new Error("User not authenticated");

    try {
      const q = query(
        collection(db, 'whatsapp_messages'),
        where('userId', '==', auth.currentUser.uid),
        where('from', 'in', [phoneNumber, 'kiara']),
        orderBy('timestamp', 'desc'),
        limit(messageLimit)
      );

      const snapshot = await getDocs(q);
      return snapshot.docs
        .map(doc => ({ id: doc.id, ...doc.data() } as WhatsAppMessage))
        .reverse();
    } catch (error) {
      console.error("Failed to fetch WhatsApp conversation:", error);
      return [];
    }
  }

  /**
   * Get all WhatsApp contacts with recent messages
   */
  async getContacts(): Promise<WhatsAppContact[]> {
    if (!auth.currentUser) throw new Error("User not authenticated");

    try {
      const q = query(
        collection(db, 'whatsapp_contacts'),
        where('userId', '==', auth.currentUser.uid),
        orderBy('lastMessageTime', 'desc')
      );

      const snapshot = await getDocs(q);
      return snapshot.docs.map(doc => ({ ...doc.data() } as WhatsAppContact));
    } catch (error) {
      console.error("Failed to fetch WhatsApp contacts:", error);
      return [];
    }
  }

  /**
   * Listen for new incoming WhatsApp messages in real-time
   */
  onNewMessage(callback: (message: WhatsAppMessage) => void): () => void {
    if (!auth.currentUser) return () => {};

    const q = query(
      collection(db, 'whatsapp_messages'),
      where('userId', '==', auth.currentUser.uid),
      where('direction', '==', 'incoming'),
      where('isProcessed', '==', false),
      orderBy('timestamp', 'desc'),
      limit(5)
    );

    return onSnapshot(q, (snapshot) => {
      snapshot.docChanges().forEach((change) => {
        if (change.type === 'added') {
          callback({ id: change.doc.id, ...change.doc.data() } as WhatsAppMessage);
        }
      });
    });
  }

  /**
   * Register the user's WhatsApp number for the integration
   */
  async registerNumber(phoneNumber: string): Promise<{ success: boolean; error?: string }> {
    if (!auth.currentUser) throw new Error("User not authenticated");

    try {
      const response = await fetch(`${this.baseUrl}/register`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          phoneNumber,
          userId: auth.currentUser.uid
        })
      });

      return await response.json();
    } catch (error: any) {
      return { success: false, error: error.message };
    }
  }

  /**
   * Get WhatsApp connection status
   */
  async getStatus(): Promise<{ connected: boolean; phoneNumber?: string; error?: string }> {
    if (!auth.currentUser) return { connected: false };

    try {
      const response = await fetch(`${this.baseUrl}/status?userId=${auth.currentUser.uid}`);
      return await response.json();
    } catch (error: any) {
      return { connected: false, error: error.message };
    }
  }
}

export const whatsappService = new WhatsAppService();
